BEGIN;

INSERT INTO des_sisi_gestor.tbl_textos_sistema (clave, valor, id_funcionalidad, usuario_modifico) VALUES
  ('gw.header.toggleNavigation', 'Toggle navigation', 114, 1),
  ('gw.header.tooltip.tareas', 'Lista de tareas', 114, 1),
  ('gw.header.tooltip.notificaciones', 'Notificaciones', 114, 1),
  ('gw.header.tooltip.mensajes', 'Mensajes', 114, 1),
  ('gw.header.tooltip.reservaciones', 'Reservaciones', 114, 1),
  ('gw.header.bienvenida', '¡Bienvenido!', 114, 1),
  ('gw.header.perfil.alt', 'Usuario', 114, 1),
  ('gw.sidebar.menu', 'Menú', 114, 1),
  ('gw.sidebar.imagenesDocumentos', 'Imágenes de documentos', 114, 1),
  ('gw.sidebar.eventoAcademico', 'Evento académico', 114, 1),
  ('gw.sidebar.responsablesEventoAcademico', 'Responsables de eventos académicos', 114, 1),
  ('gw.sidebar.convocatorias', 'Convocatorias', 114, 1),
  ('gw.sidebar.inscripciones', 'Inscripciones', 114, 1),
  ('gw.sidebar.dispersiones', 'Dispersiones', 114, 1),
  ('gw.sidebar.expedienteEstudiantesGrupo', 'Expediente de estudiantes por grupo', 114, 1),
  ('gw.sidebar.cursosDisponibles', 'Cursos disponibles', 114, 1),
  ('gw.sidebar.asignaturasDisponibles', 'Asignaturas disponibles', 114, 1),
  ('gw.sidebar.inscripcion', 'Inscripción', 114, 1),
  ('gw.sidebar.misCursos', 'Mis cursos', 114, 1),
  ('gw.sidebar.tiraMaterias', 'Tira de materias', 114, 1),
  ('gw.sidebar.misLogros', 'Mis logros', 114, 1),
  ('gw.sidebar.historialAcademico', 'Historial académico', 114, 1),
  ('gw.sidebar.reporteUsuarios', 'Reporte de usuarios', 114, 1),
  ('gw.sidebar.reporteProgramas', 'Reporte de programas', 114, 1),
  ('gw.sidebar.reporteGestionEscolar', 'Reporte de gestión escolar', 114, 1),
  ('gw.sidebar.reporteEventosCapacitacion', 'Reporte de eventos de capacitación', 114, 1),
  ('gw.sidebar.reporteAmbientesVirtuales', 'Reporte de ambientes virtuales de aprendizaje', 114, 1),
  ('gw.sidebar.areasRecursos', 'Áreas y recursos', 114, 1),
  ('gw.sidebar.programas', 'Programas', 114, 1),
  ('gw.login.boton.iniciarSesion', 'Iniciar sesión', 47, 1),
  ('gw.gestionescolar.responsables.agregar.titulo', 'Agregar responsables', 132, 1),
  ('gw.gestionescolar.responsables.etiqueta.usuario', 'Usuario', 132, 1),
  ('gw.gestionescolar.responsables.eventos.titulo', 'Responsables de eventos académicos', 132, 1),
  ('gw.gestionescolar.responsables.dialogo.eliminar.titulo', 'Eliminar responsable', 132, 1),
  ('gw.gestionescolar.responsables.dialogo.eliminar.mensaje', '¿Está seguro que desea eliminar al responsable seleccionado?', 132, 1),
  ('gw.gestionescolar.eventos.titulo', 'Eventos académicos', 72, 1),
  ('gw.gestionescolar.eventos.nuevo.titulo', 'Nuevo evento académico', 72, 1),
  ('gw.gestionescolar.eventos.dispersion.header', 'Generar dispersión', 72, 1),
  ('gw.gestionescolar.eventos.dispersion.plan', 'Plan:', 72, 1),
  ('gw.gestionescolar.eventos.dispersion.boton.dispersar', 'Dispersar', 72, 1),
  ('gw.gestionescolar.eventos.dispersion.boton.crearGrupos', 'Crear grupos', 72, 1),
  ('gw.gestionescolar.eventos.nuevo.label', 'Nuevo evento académico', 72, 1),
  ('gw.gestionescolar.eventos.busqueda.header', 'Búsqueda de eventos académicos', 72, 1),
  ('gw.gestionescolar.eventos.busqueda.plan', 'Plan:', 72, 1),
  ('gw.gestionescolar.eventos.busqueda.estructura', 'Estructura:', 72, 1),
  ('gw.gestionescolar.eventos.busqueda.subestructura1', 'Subestructura 1:', 72, 1),
  ('gw.gestionescolar.eventos.busqueda.subestructura2', 'Subestructura 2:', 72, 1),
  ('gw.gestionescolar.eventos.busqueda.subestructura3', 'Subestructura 3:', 72, 1),
  ('gw.gestionescolar.expediente.grupo.titulo', 'Expediente de estudiantes por grupo', 78, 1),
  ('gw.gestionescolar.expediente.grupo.busqueda.header', 'Búsqueda de grupo', 78, 1),
  ('gw.gestionescolar.expediente.grupo.plan', 'Plan:', 78, 1),
  ('gw.gestionescolar.expediente.grupo.estructura', 'Estructura:', 78, 1),
  ('gw.gestionescolar.calificaciones.titulo', 'Calificaciones', 75, 1),
  ('gw.gestionescolar.calificaciones.sinGrupos', 'El evento aún no tiene grupos asignados.', 75, 1),
  ('gw.gestionescolar.calificaciones.grupo', 'Grupo:', 75, 1),
  ('gw.gestionescolar.calificaciones.estatusActa', 'Estatus del acta:', 75, 1),
  ('gw.gestionescolar.calificaciones.numeroAlumnos', 'Número de alumnos', 75, 1),
  ('gw.gestionescolar.calificaciones.acta.cerrada', 'Cerrada', 75, 1),
  ('gw.gestionescolar.calificaciones.acta.abierta', 'Abierta', 75, 1),
  ('gw.gestionescolar.calificaciones.sinAlumnos', 'No hay alumnos matriculados', 75, 1),
  ('gw.gestionescolar.calificaciones.docenteLinea', 'Docente en línea', 75, 1),
  ('gw.gestionescolar.calificaciones.fechaLimite', 'Fecha límite de llenado', 75, 1),
  ('gw.gestionescolar.calificaciones.numeroEstudiantes', 'Número de estudiantes', 75, 1),
  ('gw.gestionescolar.calificaciones.duracionEvento', 'Duración del evento', 75, 1),
  ('gw.gestionescolar.calificaciones.dia', 'día', 75, 1),
  ('gw.gestionescolar.calificaciones.dias', 'días', 75, 1),
  ('gw.gestionescolar.calificaciones.generarEvaluacion.label', 'Generar evaluación:', 75, 1),
  ('gw.gestionescolar.calificaciones.generarEvaluacion.boton', 'Generar evaluación', 75, 1),
  ('gw.gestionescolar.calificaciones.importarCalificaciones', 'Importar calificaciones', 75, 1),
  ('gw.gestionescolar.calificaciones.descargarActa', 'Descargar Acta', 75, 1),
  ('gw.gestionescolar.calificaciones.cargarActaFirmada', 'Cargar Acta Firmada', 75, 1),
  ('gw.gestionescolar.calificaciones.descargaActa', 'Descarga Acta Firmada', 75, 1),
  ('gw.gestionescolar.calificaciones.eliminarActa', 'Eliminar Acta Firmada', 75, 1),
  ('gw.gestionescolar.calificaciones.confirmarActa', 'Confirmar Acta', 75, 1),
  ('gw.gestionescolar.calificaciones.col.numero', 'Número', 75, 1),
  ('gw.gestionescolar.calificaciones.col.primerApellido', 'Primer apellido', 75, 1),
  ('gw.gestionescolar.calificaciones.col.segundoApellido', 'Segundo apellido', 75, 1),
  ('gw.gestionescolar.calificaciones.col.usuario', 'Nombre de usuario', 75, 1),
  ('gw.gestionescolar.calificaciones.col.nombreEvaluacion', 'Nombre evaluación:', 75, 1),
  ('gw.gestionescolar.calificaciones.col.nombreEvaluacion.titulo', 'Nombre de la evaluación', 75, 1),
  ('gw.gestionescolar.calificaciones.col.calificacionTotal', 'Calificación total', 75, 1),
  ('gw.gestionescolar.calificaciones.col.asistencia', '% Asistencia', 75, 1),
  ('gw.gestionescolar.calificaciones.col.calificacionFinal', 'Calificación final', 75, 1),
  ('gw.gestionescolar.calificaciones.col.dictamen', 'Dictamen', 75, 1),
  ('gw.gestionescolar.calificaciones.exportarXls', 'Exportar XLS', 75, 1),
  ('gw.gestionescolar.calificaciones.boton.regresar', 'Regresar', 75, 1),
  ('gw.gestionescolar.calificaciones.dialogo.asistencias.titulo', 'Asistencias', 75, 1),
  ('gw.gestionescolar.calificaciones.dialogo.cerrarActa.titulo', 'Cerrar Acta', 75, 1),
  ('gw.gestionescolar.calificaciones.dialogo.cerrarActa.importante', '¡Importante!', 75, 1),
  ('gw.gestionescolar.calificaciones.dialogo.cerrarActa.saludo', 'Apreciable docente:', 75, 1),
  ('gw.gestionescolar.calificaciones.dialogo.cerrarActa.mensaje1', '• La generación de actas de calificaciones del periodo escolar vigente se habilita conforme a lo señalado en el calendario académico, esto depende del programa educativo en el que participa. No olvide atender las solicitudes de aclaración.', 75, 1),
  ('gw.gestionescolar.calificaciones.dialogo.cerrarActa.mensaje2', '• Conserve el acta original firmada en dos tantos con tinta azul pues, en apego a las disposiciones de la SEP y de la Secretaria de Salud se harán las notificaciones oportunas para su entrega.', 75, 1),
  ('gw.gestionescolar.calificaciones.dialogo.cerrarActa.mensaje3', '• Le recordamos que las actas de calificaciones tanto originales como en el SIGIE representan el soporte de los estudios cursados por nuestros estudiantes, por ello, si tiene faltantes complételas a la brevedad.', 75, 1),
  ('gw.gestionescolar.calificaciones.dialogo.cerrarActa.confirmacion', 'Confirmar que desea cerrar actas, esta acción no se podrá revertir', 75, 1),
  ('gw.gestionescolar.calificaciones.dialogo.cerrarActa.cancelar', 'Cancelar', 75, 1),
  ('gw.gestionescolar.calificaciones.dialogo.cerrarActa.aceptar', 'Aceptar', 75, 1),
  ('gw.gestionescolar.calificaciones.dialogo.cargarActa.titulo', 'Carga Acta de calificaciones firmada', 75, 1),
  ('gw.gestionescolar.calificaciones.dialogo.cargarActa.label', 'Cargar Acta:', 75, 1),
  ('gw.gestionescolar.calificaciones.dialogo.cargarActa.btn.elegir', 'Elegir', 75, 1),
  ('gw.gestionescolar.calificaciones.dialogo.cargarActa.btn.cargar', 'Cargar', 75, 1),
  ('gw.gestionescolar.calificaciones.dialogo.cargarActa.btn.cancelar', 'Cancelar', 75, 1),
  ('gw.gestionescolar.calificaciones.dialogo.cargarActa.fileLimit', 'Solo se permite cargar un archivo', 75, 1),
  ('gw.gestionescolar.calificaciones.visor.constancia', 'Constancia', 75, 1),
  ('gw.gestionescolar.calificaciones.visor.actaFirmada', 'Acta Firmada', 75, 1),
  ('gw.gestionescolar.chat.usuariosConectados', 'Usuarios conectados', 73, 1),
  ('gw.mensajes.texto.detalle', 'Detalle del mensaje', 65, 1),
  ('gw.mensajes.detalle.adjunto', 'El mensaje contiene un archivo adjunto:', 65, 1),
  ('gw.mensajes.detalle.adjunto.descargar', 'Descargar', 65, 1),
  ('gw.mensajes.texto.seleccionarDestinatarios', 'Seleccionar destinatarios', 65, 1),
  ('gw.mensajes.texto.nombreUsuario', 'Nombre de usuario:', 65, 1),
  ('gw.mensajes.texto.todosSeleccionados', 'Todos los seleccionados:', 65, 1),
  ('gw.admin.parametros.correo.titulo', 'Configuración de correo', 117, 1),
  ('gw.admin.parametros.correo.panel.servidor', 'Configuración de servidor y cuenta de correo', 117, 1),
  ('gw.admin.parametros.correo.host', 'Nombre del Host de correo:', 117, 1),
  ('gw.admin.parametros.correo.puerto', 'Puerto de correo:', 117, 1),
  ('gw.admin.parametros.correo.cuenta', 'Cuenta de correo:', 117, 1),
  ('gw.admin.parametros.correo.contrasena', 'Contraseña de correo:', 117, 1),
  ('gw.admin.parametros.correo.boton.guardar', 'Guardar', 117, 1),
  ('gw.admin.parametros.correo.panel.envio', 'Envió de Correo', 117, 1),
  ('gw.admin.parametros.correo.para', 'Para:', 117, 1),
  ('gw.admin.parametros.correo.boton.agregar', 'Agregar', 117, 1),
  ('gw.admin.parametros.correo.col.destinatario', 'Destinatario', 117, 1),
  ('gw.admin.parametros.correo.col.eliminar', 'Eliminar', 117, 1),
  ('gw.admin.parametros.correo.boton.eliminar', 'Eliminar', 117, 1),
  ('gw.admin.parametros.correo.cc', 'CC:', 117, 1),
  ('gw.admin.parametros.correo.asunto', 'Asunto:', 117, 1),
  ('gw.admin.parametros.correo.boton.enviar', 'Enviar', 117, 1),
  ('gw.bitacora.seleccionarPersona', 'Seleccionar persona', 58, 1),
  ('gw.temas.archivos.listado.titulo', 'Ver listado de archivos del tema', 153, 1),
  ('gw.cargamasiva.label.ver', 'Ver', 131, 1),
  ('gw.cargamasiva.archivo.formatos', '(.csv, .xls, .xlsl)', 131, 1),
  ('gw.cargamasiva.modal.col.tipoUsuario', 'Tipo de usuario: (INTERNO/EXTERNO)', 131, 1),
  ('gw.cargamasiva.modal.col.usuario', 'Usuario: (Alfanumérico)', 131, 1),
  ('gw.cargamasiva.modal.col.contrasena', 'Contraseña:(Alfanumérico)', 131, 1),
  ('gw.cargamasiva.modal.col.programaSocial', 'Programa social: (SI/NO)', 131, 1),
  ('gw.cargamasiva.modal.col.curp', 'CURP:', 131, 1),
  ('gw.cargamasiva.modal.col.nombre', 'Nombre:(TEXTO)', 131, 1),
  ('gw.cargamasiva.modal.col.primerApellido', 'Primer apellido:(TEXTO)', 131, 1),
  ('gw.cargamasiva.modal.col.segundoApellido', 'Segundo apellido:(TEXTO)', 131, 1),
  ('gw.cargamasiva.modal.col.fechaNacimiento', 'Fecha de nacimiento (DD/MM/AA)', 131, 1),
  ('gw.cargamasiva.modal.col.institucion', 'Institución:(TEXTO)', 131, 1),
  ('gw.cargamasiva.modal.col.correo', 'Correo electrónico:', 131, 1),
  ('gw.cargamasiva.modal.col.telefono', 'Teléfono:', 131, 1),
  ('gw.cargamasiva.modal.col.celular', 'Celular:', 131, 1),
  ('gw.cargamasiva.modal.col.sede', 'Sede: (ESTADO)', 131, 1),
  ('gw.cargamasiva.modal.col.municipio', 'Municipio o delegación', 131, 1),
  ('gw.cargamasiva.modal.col.ordenGobierno', 'Orden de gobierno: (FEDERAL, ESTATAL, MUNICIPAL, OTRO)', 131, 1),
  ('gw.cargamasiva.modal.col.puesto', 'Puesto:(TEXTO)', 131, 1),
  ('gw.cargamasiva.modal.col.idConvocatoria', 'Id de convocatoria: (AGREGAR 0 SI NO SE VINCULARÁ USUARIO)', 131, 1),
  ('gw.cargamasiva.modal.col.idPlan', 'Id plan: (AGREGAR 0 SI NO SE VINCULARÁ USUARIO)', 131, 1),
  ('gw.alumno.miPerfil.titulo', 'Mi perfil', 175, 1),
  ('gw.alumno.logros.titulo', 'Mis logros', 188, 1),
  ('gw.alumno.constancias.historial', 'Historial académico', 189, 1),
  ('gw.alumno.constancias.historialEstudiante', 'Historial académico del estudiante', 189, 1),
  ('gw.alumno.constancias.matricula', 'Matricula', 189, 1),
  ('gw.alumno.constancias.programaEducativo', 'Programa Educativo', 189, 1),
  ('gw.alumno.constancias.promedio', 'Promedio', 189, 1),
  ('gw.alumno.constancias.creditos', 'Créditos', 189, 1),
  ('gw.alumno.constancias.aprobadas', 'Aprobadas', 189, 1),
  ('gw.alumno.constancias.reprobadas', 'Reprobadas', 189, 1),
  ('gw.alumno.constancias.noPresentadas', 'No Presentadas', 189, 1),
  ('gw.alumno.constancias.total', 'Total', 189, 1),
  ('gw.alumno.constancias.estatus', 'Estatus', 189, 1),
  ('gw.alumno.constancias.nivel', 'Nivel', 189, 1),
  ('gw.alumno.constancias.fechaConsulta', 'Fecha de Consulta', 189, 1),
  ('gw.alumno.constancias.encuestaPendiente', 'Para poder visualizar su constancia debe contestar la encuesta.', 189, 1),
  ('gw.alumno.constancias.imprimir', 'Imprimir', 189, 1),
  ('gw.alumno.constancias.regresar', 'Regresar', 189, 1),
  ('gw.alumno.constancias.cerrar', 'Cerrar', 189, 1),
  ('gw.alumno.constancias.modal.constancia', 'Constancia', 189, 1),
  ('gw.alumno.misCursos.titulo', 'Tira de materias', 186, 1),
  ('gw.alumno.misCursos.header', 'Información de las asignaturas en proceso', 186, 1),
  ('gw.alumno.misCursos.programaEducativo', 'Programa educativo', 186, 1),
  ('gw.alumno.misCursos.matricula', 'Matricula', 186, 1),
  ('gw.alumno.misCursos.columna.asignatura', 'Nombre de las asignaturas', 186, 1),
  ('gw.alumno.misCursos.columna.clave', 'Clave', 186, 1),
  ('gw.alumno.misCursos.columna.bloque', 'Bloque / Módulo', 186, 1),
  ('gw.alumno.misCursos.columna.grupo', 'Grupo', 186, 1),
  ('gw.alumno.misCursos.columna.docente', 'Docente', 186, 1),
  ('gw.alumno.misCursos.columna.asesor', 'Asesor', 186, 1),
  ('gw.alumno.convocatorias.titulo', 'Convocatorias', 210, 1),
  ('gw.alumno.convocatorias.nueva', 'Nueva convocatoria', 210, 1),
  ('gw.alumno.convocatorias.consultar', 'Consultar convocatoria', 210, 1),
  ('gw.alumno.convocatorias.tablero', 'Consultar tablero de resumen', 210, 1),
  ('gw.alumno.inscripciones.titulo', 'Inscripciones', 211, 1),
  ('gw.alumno.inscripciones.nuevo', 'Nuevo proceso de inscripción', 211, 1),
  ('gw.alumno.inscripciones.consultar', 'Consultar proceso de inscripción', 211, 1),
  ('gw.alumno.inscripciones.tablero', 'Consultar tablero resumen', 211, 1),
  ('gw.alumno.dispersiones.titulo', 'Dispersiones', 212, 1),
  ('gw.alumno.dispersiones.proceso', 'Proceso de dispersión', 212, 1),
  ('gw.alumno.dispersiones.nuevo', 'Nuevo proceso de dispersión', 212, 1),
  ('gw.alumno.dispersiones.consultar', 'Consultar dispersión', 212, 1),
  ('gw.alumno.dispersiones.tablero', 'Dispersión', 212, 1),
  ('gw.alumno.constancias.noActa', 'No. acta', 189, 1),
  ('gw.alumno.constancias.modalidad', 'Modalidad', 189, 1),
  ('gw.alumno.constancias.fechaFinalizacion', 'Fecha de finalización', 189, 1),
  ('gw.alumno.constancias.encuestaFinal', 'Encuesta final', 189, 1),
  ('gw.alumno.constancias.promedioEvaluaciones', 'Promedio de evaluaciones', 189, 1),
  ('gw.alumno.constancias.porcentajeAsistencias', 'Porcentaje de asistencias', 189, 1),
  ('gw.alumno.constancias.calificacionFinal', 'Calificación final', 189, 1),
  ('gw.alumno.constancias.col.constancias', 'Constancias', 189, 1),
  ('gw.alumno.constancias.ver', 'Ver', 189, 1),
  ('gw.alumno.constancias.noAplica', 'No aplica', 189, 1),
  ('gw.alumno.constancias.reporte.titulo', 'Expediente académico', 189, 1),
  ('gw.gestionaprendizaje.expediente.verEstudiante', 'Ver expediente del estudiante', 189, 1),
  ('gw.alumno.constancias.col.nombreGrupo', 'Nombre del Grupo', 189, 1),
  ('gw.alumno.inscripcion.titulo', 'Inscripción', 211, 1),
  ('gw.alumno.inscripcion.aceptar', 'Acepto los', 211, 1),
  ('gw.alumno.inscripcion.terminos', 'términos y condiciones', 211, 1),
  ('gw.alumno.inscripcion.finalizar', 'Finalizar inscripción', 211, 1),
  ('gw.alumno.inscripcion.informativo', 'Informativo', 211, 1),
  ('gw.gamificacion.badges.titulo', 'Badges', 182, 1),
  ('gw.gamificacion.badges.clasificacion', 'Clasificación badges', 182, 1),
  ('gw.gamificacion.badges.nuevaClasificacion', 'Nueva clasificación', 182, 1),
  ('gw.gamificacion.badges.eliminar', 'Eliminar', 182, 1),
  ('gw.gamificacion.badges.dialogo.editar', 'Editar', 182, 1),
  ('gw.alumno.cursos.titulo', 'Cursos disponibles', 182, 1),
  ('gw.alumno.cursos.buscar', 'Buscar cursos', 182, 1),
  ('gw.alumno.cursos.nivel', 'Nivel:', 182, 1),
  ('gw.alumno.cursos.duracion', 'Duración (días):', 182, 1),
  ('gw.alumno.cursos.valoracion', 'Valoración del curso por los participantes:', 182, 1),
  ('gw.alumno.cursos.solicitar', 'Solicitar', 182, 1),
  ('gw.analisis.titulo', 'Análisis de datos', 92, 1),
  ('gw.analisis.reporteUsuarios.titulo', 'Reporte de usuarios', 92, 1),
  ('gw.analisis.reporteUsuarios.busqueda.titulo', 'Búsqueda de datos del usuario', 92, 1),
  ('gw.analisis.reporteUsuarios.clasificacion', 'Clasificación de usuario:', 92, 1),
  ('gw.analisis.reporteUsuarios.estatus', 'Estatus:', 92, 1),
  ('gw.analisis.reporteUsuarios.estado', 'Estado:', 92, 1),
  ('gw.analisis.reporteUsuarios.ciudad', 'Ciudad o municipio:', 92, 1),
  ('gw.analisis.reporteUsuarios.genero', 'Género:', 92, 1),
  ('gw.analisis.reporteUsuarios.rangoEdad', 'Rango de edad:', 92, 1),
  ('gw.analisis.reporteUsuarios.fechaInicial', 'Inicial:', 92, 1),
  ('gw.analisis.reporteUsuarios.fechaFinal', 'Final:', 92, 1),
  ('gw.analisis.reporteUsuarios.limpiar', 'Limpiar campos', 92, 1),
  ('gw.analisis.reporteUsuarios.buscar', 'Buscar', 92, 1),
  ('gw.analisis.reporteUsuarios.resultado', 'Resultado de la búsqueda', 92, 1),
  ('gw.analisis.reporteUsuarios.instruccion', 'Para agregar más datos en tu reporte, selecciona en el siguiente menú los necesarios.', 92, 1),
  ('gw.analisis.reporteUsuarios.columnaDatos', 'Columna de datos', 92, 1),
  ('gw.analisis.reporteUsuarios.col.estatus', 'Estatus', 92, 1),
  ('gw.analisis.reporteUsuarios.col.clasificacion', 'Clasificación', 92, 1),
  ('gw.analisis.reporteUsuarios.col.nombre', 'Nombre', 92, 1),
  ('gw.analisis.reporteUsuarios.col.apellidoPaterno', 'Apellido paterno', 92, 1),
  ('gw.analisis.reporteUsuarios.col.apellidoMaterno', 'Apellido materno', 92, 1),
  ('gw.analisis.reporteUsuarios.col.fechaRegistro', 'Fecha registro', 92, 1),
  ('gw.analisis.reporteUsuarios.col.entidad', 'Entidad Federativa', 92, 1),
  ('gw.analisis.reporteUsuarios.col.genero', 'Género', 92, 1),
  ('gw.analisis.reporteUsuarios.col.institucion', 'Institución', 92, 1),
  ('gw.analisis.reporteUsuarios.col.unidadAdscripcion', 'Unidad de adscripción', 92, 1),
  ('gw.analisis.reporteUsuarios.col.areaAdscripcion', 'Área de adscripción', 92, 1),
  ('gw.analisis.reporteUsuarios.col.programaSocial', 'Pertenece a un programa social', 92, 1),
  ('gw.analisis.reporteUsuarios.col.puesto', 'Puesto', 92, 1),
  ('gw.analisis.reporteUsuarios.col.ordenGobierno', 'Orden de gobierno', 92, 1),
  ('gw.analisis.reporteUsuarios.col.roles', 'Roles', 92, 1),
  ('gw.analisis.reporteUsuarios.col.edad', 'Edad', 92, 1),
  ('gw.analisis.reporteUsuarios.valor.externo', 'Externo', 92, 1),
  ('gw.analisis.reporteUsuarios.valor.interno', 'Interno', 92, 1),
  ('gw.analisis.reporteUsuarios.valor.activo', 'Activo', 92, 1),
  ('gw.analisis.reporteUsuarios.valor.inactivo', 'Inactivo', 92, 1),
  ('gw.analisis.reporteUsuarios.valor.si', 'Sí', 92, 1),
  ('gw.analisis.reporteUsuarios.valor.no', 'No', 92, 1),
  ('gw.analisis.reporteUsuarios.valor.activos', 'Activos', 92, 1),
  ('gw.analisis.reporteUsuarios.reporteExcel', 'Reporte de excel:', 92, 1),
  ('gw.analisis.reporteUsuarios.descargar', 'Descargar', 92, 1),
  ('gw.analisis.reporteUsuarios.informePredisenado', 'Informe prediseñado:', 92, 1),
  ('gw.analisis.reporteUsuarios.generar', 'Generar', 92, 1),
  ('gw.analisis.reporteUsuarios.modal.titulo.estado', 'Usuarios por entidad federativa', 92, 1),
  ('gw.analisis.reporteUsuarios.modal.titulo.general', 'Informe prediseñado general de usuarios', 92, 1),
  ('gw.analisis.reporteUsuarios.modal.registroUsuarios', 'REGISTRO DE USUARIOS QUE', 92, 1),
  ('gw.analisis.reporteUsuarios.modal.y', 'y', 92, 1),
  ('gw.analisis.reporteUsuarios.modal.entidad', 'ENTIDAD FEDERATIVA', 92, 1),
  ('gw.analisis.reporteUsuarios.modal.municipio', 'CIUDAD O MUNICIPIO', 92, 1),
  ('gw.analisis.reporteUsuarios.modal.total', 'TOTAL', 92, 1),
  ('gw.analisis.reporteUsuarios.modal.tiposUsuarios', 'TIPOS DE USUARIOS', 92, 1),
  ('gw.analisis.reporteUsuarios.modal.enLinea', 'EN LINEA', 92, 1),
  ('gw.analisis.reporteUsuarios.graf.genero', 'GENERO', 92, 1),
  ('gw.analisis.reporteUsuarios.graf.estatusUsuarios', 'ESTATUS DE USUARIOS', 92, 1),
  ('gw.analisis.reporteUsuarios.graf.ordenGobierno', 'USUARIOS POR ORDEN DE GOBIERNO', 92, 1),
  ('gw.analisis.reporteUsuarios.graf.puesto', 'USUARIOS POR PUESTO', 92, 1),
  ('gw.analisis.reporteUsuarios.graf.rangoEdades', 'USUARIOS POR RANGO DE EDADES', 92, 1),
  ('gw.analisis.reporteUsuarios.graf.nivelConocimientos', 'NIVEL DE CONOCIMIENTOS', 92, 1),
  ('gw.analisis.reporteUsuarios.graf.nivelEnsenanza', 'NIVEL DE ENSEÑANZA', 92, 1),
  ('gw.analisis.reporteUsuarios.graf.modalidad', 'MODALIDAD', 92, 1),
  ('gw.analisis.reporteUsuarios.cerrar', 'Cerrar', 92, 1),
  ('gw.analisis.graficas.programas', 'Programas', 92, 1),
  ('gw.analisis.graficas.estadisticasProgramas', 'Estadísticas Programas', 92, 1),
  ('gw.analisis.graficas.modal.titulo', 'Programas de capacitación', 92, 1),
  ('gw.analisis.graficas.total', 'TOTAL', 92, 1),
  ('gw.analisis.graficas.tipoCompetencia', 'TIPO DE COMPETENCIA', 92, 1),
  ('gw.analisis.graficas.estrategicos', 'Estratégicos', 92, 1),
  ('gw.analisis.graficas.gestion', 'De gestión', 92, 1),
  ('gw.analisis.graficas.programaEstrategico', 'PROGRAMA DE TIPO ESTRATÉGICO', 92, 1),
  ('gw.analisis.graficas.programaGestion', 'PROGRAMA DE TIPO DE GESTIÓN', 92, 1),
  ('gw.analisis.graficas.programasAreaResponsable', 'NUM. DE PROGRAMAS POR ÁREA RESPONSABLE', 92, 1),
  ('gw.analisis.graficas.programasTipoEvento', 'NUM. DE PROGRAMAS POR TIPO DE EVENTO DE CAPACITACIÓN', 92, 1),
  ('gw.analisis.graficas.nivelConocimientos', 'NIVEL DE CONOCIMIENTOS', 92, 1),
  ('gw.analisis.graficas.nivelEnsenanza', 'NIVEL DE ENSEÑANZA', 92, 1),
  ('gw.analisis.graficas.modalidad', 'MODALIDAD', 92, 1),
  ('gw.analisis.graficas.estatus', 'ESTATUS', 92, 1),
  ('gw.analisis.reporteAmbientes.titulo', 'Reporte de ambientes virtuales de aprendizaje', 92, 1),
  ('gw.analisis.reporteAmbientes.busqueda.titulo', 'Búsqueda de datos en gestión del aprendizaje', 92, 1),
  ('gw.analisis.reporteAmbientes.tipoCompetencia', 'Tipo de competencia:', 92, 1),
  ('gw.analisis.reporteAmbientes.ejeCapacitacion', 'Eje de capacitación:', 92, 1),
  ('gw.analisis.reporteAmbientes.modalidad', 'Modalidad:', 92, 1),
  ('gw.analisis.reporteAmbientes.nivelEnsenanza', 'Nivel de enseñanza:', 92, 1),
  ('gw.analisis.reporteAmbientes.estatus', 'Estatus:', 92, 1),
  ('gw.analisis.reporteAmbientes.tipoRangoFecha', 'Tipo de rango de fecha:', 92, 1),
  ('gw.analisis.reporteAmbientes.fechaInicial', 'Fecha inicial:', 92, 1),
  ('gw.analisis.reporteAmbientes.fechaFinal', 'Fecha final:', 92, 1),
  ('gw.analisis.columnas.clave', 'Clave', 92, 1),
  ('gw.analisis.columnas.nombreEvento', 'Nombre del evento', 92, 1),
  ('gw.analisis.columnas.tipoCompetencia', 'Tipo de competencia', 92, 1),
  ('gw.analisis.columnas.ejeCapacitacion', 'Eje de capacitación', 92, 1),
  ('gw.analisis.columnas.modalidad', 'Modalidad', 92, 1),
  ('gw.analisis.columnas.estatus', 'Estatus', 92, 1),
  ('gw.analisis.columnas.fechaInicial', 'Fecha inicial', 92, 1),
  ('gw.analisis.columnas.fechaFinal', 'Fecha final', 92, 1),
  ('gw.analisis.columnas.id', 'ID', 92, 1),
  ('gw.analisis.columnas.nombrePrograma', 'Nombre del Programa', 92, 1),
  ('gw.analisis.columnas.expediente', 'Expediente', 92, 1),
  ('gw.analisis.reporteEventos.titulo', 'Reporte de eventos de capacitación', 92, 1),
  ('gw.analisis.reporteEventos.busqueda.titulo', 'Búsqueda de eventos de capacitación', 92, 1),
  ('gw.analisis.reporteEventos.programa', 'Nombre del programa de capacitación: ', 92, 1),
  ('gw.analisis.reporteEventos.evento', 'Nombre del evento de capacitación: ', 92, 1),
  ('gw.analisis.reporteEventos.entidad', 'Entidad federativa:', 92, 1),
  ('gw.analisis.reporteEventos.municipio', 'Ciudad o municipio:', 92, 1),
  ('gw.analisis.reporteEventos.col.tieneProgramaSocial', '¿Cuenta con programa social?', 92, 1),
  ('gw.analisis.reporteEventos.col.programaSocial', 'Programa social', 92, 1),
  ('gw.analisis.reporteEventos.col.unidadResponsable', 'Unidad responsable', 92, 1),
  ('gw.analisis.reporteEventos.col.entidad', 'Entidad federativa', 92, 1),
  ('gw.analisis.reporteEventos.col.municipio', 'Municipio', 92, 1),
  ('gw.analisis.reporteEventos.col.usuariosRegistrados', 'Usuarios registrados', 92, 1),
  ('gw.analisis.reporteEventos.col.usuariosFinalizaron', 'Usuarios que finalizaron', 92, 1),
  ('gw.analisis.reporteEventos.col.usuariosAprobados', 'Cantidad usuarios aprobados', 92, 1),
  ('gw.analisis.reporteEventos.col.usuariosReprobados', 'Cantidad usuarios reprobados', 92, 1),
  ('gw.analisis.reporteEventos.col.promedioEvento', 'Promedio del evento de capacitación', 92, 1),
  ('gw.analisis.reporteEventos.modal.expediente', 'Expediente del evento', 92, 1),
  ('gw.analisis.reporteEventosCap.titulo', 'Reporte de eventos de capacitación', 92, 1),
  ('gw.analisis.reporteEventosCap.busqueda.titulo', 'Búsqueda de datos del evento del capacitación', 92, 1),
  ('gw.analisis.reporteEventosCap.tipoCompetencia', 'Tipo de competencia:', 92, 1),
  ('gw.analisis.reporteEventosCap.ejeCapacitacion', 'Eje de capacitación:', 92, 1),
  ('gw.analisis.reporteEventosCap.modalidad', 'Modalidad', 92, 1),
  ('gw.analisis.reporteEventosCap.estatus', 'Estatus', 92, 1),
  ('gw.analisis.reporteEventosCap.fechaRegistro', 'Fecha registro:', 92, 1),
  ('gw.analisis.reporteEventosCap.fechaInicial', 'Inicial:', 92, 1),
  ('gw.analisis.reporteEventosCap.fechaFinal', 'Final:', 92, 1),
  ('gw.analisis.reporteEventosCap.col.nombrePrograma', 'Nombre del programa de capacitación', 92, 1),
  ('gw.analisis.reporteEventosCap.col.claveEc', 'Clave del EC', 92, 1),
  ('gw.analisis.reporteEventosCap.col.nombreEc', 'Nombre del EC', 92, 1),
  ('gw.analisis.reporteEventosCap.col.nivelEnsenanza', 'Nivel de enseñanza', 92, 1),
  ('gw.analisis.reporteEventosCap.col.dirigidoA', 'Dirigido a', 92, 1),
  ('gw.analisis.reporteEventosCap.col.destinatarios', 'Destinatarios', 92, 1),
  ('gw.analisis.reporteEventosCap.col.categoria', 'Categoria', 92, 1),
  ('gw.analisis.reporteEventosCap.col.coordinador', 'Coordinador Academico', 92, 1),
  ('gw.analisis.reporteEventosCap.col.numeroParticipantes', 'Numero Participantes', 92, 1),
  ('gw.analisis.reporteEventosCap.col.hombres', 'Hombres', 92, 1),
  ('gw.analisis.reporteEventosCap.col.mujeres', 'Mujeres', 92, 1),
  ('gw.analisis.reporteEventosCap.col.porcentajeAsistencias', 'Porcentaje de asistencias', 92, 1),
  ('gw.analisis.reporteEventosCap.col.tipoEvento', 'Tipo de evento de capacitación', 92, 1),
  ('gw.analisis.reporteGestion.titulo', 'Reporte de gestión escolar', 92, 1),
  ('gw.analisis.reporteGestion.busqueda.titulo', 'Búsqueda de eventos de capacitación', 92, 1),
  ('gw.analisis.reporteGestion.entidad', 'Entidad federativa:', 92, 1),
  ('gw.analisis.reporteGestion.municipio', 'Ciudad o municipio:', 92, 1),
  ('gw.analisis.reporteGestion.tipoCompetencia', 'Tipo de competencia:', 92, 1),
  ('gw.analisis.reporteGestion.ejeCapacitacion', 'Eje de capacitación:', 92, 1),
  ('gw.analisis.reporteGestion.modalidad', 'Modalidad:', 92, 1),
  ('gw.analisis.reporteGestion.evento', 'Nombre del evento de capacitación: ', 92, 1),
  ('gw.analisis.reporteGestion.clasificacionInfo', 'Clasificación de la información:', 92, 1),
  ('gw.analisis.reporteGestion.valorPrivado', 'Privado', 92, 1),
  ('gw.analisis.reporteGestion.valorPublico', 'Público', 92, 1),
  ('gw.analisis.reporteGestion.tipoEvento', 'Tipo de evento:', 92, 1),
  ('gw.analisis.reporteGestion.dirigidoA', 'Dirigido a:', 92, 1),
  ('gw.analisis.reporteGestion.col.nivelConocimiento', 'Nivel de conocimiento', 92, 1),
  ('gw.analisis.reporteGestion.col.participantes', 'Número de participantes', 92, 1),
  ('gw.analisis.reporteGestion.col.ubicacion', 'Ubicación geográfica', 92, 1),
  ('gw.analisis.reporteGestion.col.promedioAsistencias', 'Promedio de asistencias', 92, 1),
  ('gw.analisis.reporteGestion.col.promedioCalificaciones', 'Promedio de calificaciones', 92, 1),
  ('gw.analisis.reporteGestion.modal.tituloEstado', 'Eventos de capacitación por entidad federativa', 92, 1),
  ('gw.analisis.reporteGestion.modal.tituloGeneral', 'Informe prediseñado general de eventos de capacitación', 92, 1),
  ('gw.analisis.reporteGestion.modal.eventosQue', 'EVENTOS QUE', 92, 1),
  ('gw.analisis.reporteGestion.modal.entidad', 'ENTIDAD FEDERATIVA', 92, 1),
  ('gw.analisis.reporteGestion.modal.total', 'TOTAL', 92, 1),
  ('gw.analisis.reporteGestion.modal.eventos', 'Eventos', 92, 1),
  ('gw.analisis.reporteGestion.modal.eventosTipoCompetencia', 'CANTIDAD DE EVENTOS POR TIPO DE COMPETENCIA', 92, 1),
  ('gw.analisis.reporteGestion.modal.eventosEjeCapacitacion', 'CANTIDAD DE EVENTOS POR EJE DE CAPACITACIÓN', 92, 1),
  ('gw.analisis.reporteGestion.modal.eventosPrograma', 'CANTIDAD DE EVENTOS POR PROGRAMA', 92, 1),
  ('gw.analisis.reporteGestion.modal.verProgramas', 'Ver lista de programas', 92, 1),
  ('gw.analisis.reporteGestion.modal.modalidad', 'MODALIDAD:', 92, 1),
  ('gw.analisis.reporteGestion.modal.clasificacion', 'CLASIFICACIÓN DE LA INFORMACIÓN', 92, 1),
  ('gw.analisis.reporteGestion.modal.tipoEvento', 'TIPO DE EVENTO:', 92, 1),
  ('gw.analisis.reporteGestion.modal.dirigidoExternos', 'DIRIGIDO A USUARIOS EXTERNOS:', 92, 1),
  ('gw.analisis.reporteGestion.modal.eventosEntidad', 'CANTIDAD DE EVENTOS POR ENTIDAD FEDERATIVA', 92, 1),
  ('gw.analisis.reporteProgramas.titulo', 'Reporte de programas', 92, 1),
  ('gw.analisis.reporteProgramas.busqueda.titulo', 'Búsqueda de programas', 92, 1),
  ('gw.analisis.reporteProgramas.tipoCompetencia', 'Tipo de competencia:', 92, 1),
  ('gw.analisis.reporteProgramas.ejeCapacitacion', 'Eje de capacitación:', 92, 1),
  ('gw.analisis.reporteProgramas.modalidad', 'Modalidad:', 92, 1),
  ('gw.analisis.reporteProgramas.nivelEnsenanza', 'Nivel de enseñanza:', 92, 1),
  ('gw.analisis.reporteProgramas.estatus', 'Estatus:', 92, 1),
  ('gw.analisis.reporteProgramas.col.ejeCompetencia', 'Eje de competencia', 92, 1),
  ('gw.analisis.reporteProgramas.col.competenciaEspecifica', 'Competencia específica', 92, 1),
  ('gw.analisis.reporteProgramas.col.areaResponsable', 'Área responsable', 92, 1),
  ('gw.analisis.reporteProgramas.col.tipoEvento', 'Tipo de evento', 92, 1),
  ('gw.analisis.reporteProgramas.col.seriado', 'Seriado', 92, 1),
  ('gw.analisis.reporteProgramas.col.ecPorPrograma', 'Número de EC por programa', 92, 1),
  ('gw.analisis.reporteProgramas.modal.tituloEstado', 'Programas por entidad federativa', 92, 1),
  ('gw.analisis.reporteProgramas.modal.tituloGeneral', 'Informe prediseñado general de programas', 92, 1),
  ('gw.analisis.reporteProgramas.modal.programasQue', 'PROGRAMAS QUE', 92, 1),
  ('gw.analisis.reporteProgramas.modal.entidad', 'ENTIDAD FEDERATIVA', 92, 1),
  ('gw.analisis.reporteProgramas.modal.total', 'TOTAL', 92, 1),
  ('gw.analisis.reporteProgramas.modal.programas', 'Programas', 92, 1),
  ('gw.analisis.reporteProgramas.modal.programasTipoCompetencia', 'CANTIDAD DE PROGRAMAS POR TIPO DE COMPETENCIA', 92, 1),
  ('gw.analisis.reporteProgramas.modal.programasEjeCapacitacion', 'CANTIDAD DE PROGRAMAS POR EJE DE CAPACITACIÓN', 92, 1),
  ('gw.analisis.reporteProgramas.modal.programasPorPrograma', 'CANTIDAD DE PROGRAMAS POR PROGRAMA', 92, 1),
  ('gw.analisis.reporteProgramas.modal.verProgramas', 'Ver lista de programas', 92, 1),
  ('gw.analisis.reporteProgramas.modal.modalidad', 'MODALIDAD:', 92, 1),
  ('gw.analisis.reporteProgramas.modal.clasificacion', 'CLASIFICACIÓN DE LA INFORMACIÓN', 92, 1),
  ('gw.analisis.reporteProgramas.modal.tipoEvento', 'TIPO DE EVENTO:', 92, 1),
  ('gw.analisis.reporteProgramas.modal.dirigidoExternos', 'DIRIGIDO A USUARIOS EXTERNOS:', 92, 1),
  ('gw.analisis.reporteProgramas.modal.programasEntidad', 'CANTIDAD DE PROGRAMAS POR ENTIDAD FEDERATIVA', 92, 1),
  ('gw.analisis.reporteReservaciones.titulo', 'Áreas y recursos', 92, 1),
  ('gw.analisis.reporteReservaciones.busqueda.titulo', 'Búsqueda de reservaciones de áreas', 92, 1),
  ('gw.analisis.reporteReservaciones.sede', 'Sede:', 92, 1),
  ('gw.analisis.reporteReservaciones.area', 'Área:', 92, 1),
  ('gw.analisis.reporteReservaciones.tipoEvento', 'Tipo evento:', 92, 1),
  ('gw.analisis.reporteReservaciones.estatus', 'Estatus reservación:', 92, 1),
  ('gw.analisis.reporteReservaciones.fechaInicial', 'Fecha de registro inicial:', 92, 1),
  ('gw.analisis.reporteReservaciones.fechaFinal', 'Fecha de registro final:', 92, 1),
  ('gw.analisis.reporteReservaciones.col.area', 'Área', 92, 1),
  ('gw.analisis.reporteReservaciones.col.tipoEvento', 'Tipo de evento', 92, 1),
  ('gw.analisis.reporteReservaciones.col.nombreEvento', 'Nombre del evento', 92, 1),
  ('gw.analisis.reporteReservaciones.col.eventoPrivado', 'Evento privado', 92, 1),
  ('gw.analisis.reporteReservaciones.col.solicitante', 'Solicitante', 92, 1),
  ('gw.analisis.reporteReservaciones.col.estatus', 'Estatus reservación', 92, 1),
  ('gw.analisis.reporteReservaciones.col.fechaSolicitud', 'Fecha de solicitud', 92, 1),
  ('gw.analisis.reporteReservaciones.col.distribucion', 'Distribución', 92, 1),
  ('gw.analisis.reporteReservaciones.col.servicioCafeteria', 'Servicio de cafetería', 92, 1),
  ('gw.analisis.reporteReservaciones.col.horaInicio', 'Hora de inicio', 92, 1),
  ('gw.analisis.reporteReservaciones.col.horaFin', 'Hora de término', 92, 1),
  ('gw.analisis.reporteReservaciones.col.ubicacion', 'Ubicación', 92, 1),
  ('gw.analisis.reporteReservaciones.col.sede', 'Sede', 92, 1),
  ('gw.analisis.reporteReservaciones.modal.titulo', 'Informe prediseñado general de reservaciones', 92, 1),
  ('gw.encuestas.responder.breadcrumb', 'Encuesta', 86, 1),
  ('gw.encuestas.responder.titulo', 'Contestar encuesta', 86, 1),
  ('gw.encuestas.responder.mensajeSistema', 'Mensaje del sistema', 86, 1),
  ('gw.gamificacion.badges.descripcion', 'Descripción', 182, 1),
  ('gw.home.breadcrumb', 'Tablero de control.', 186, 1),
  ('gw.home.titulo', 'Tablero de control.', 186, 1),
  ('gw.home.card.calendario', 'Calendario', 186, 1),
  ('gw.home.card.correo', 'Correo', 186, 1),
  ('gw.home.card.repositorio', 'Repositorio', 186, 1),
  ('gw.home.card.ayuda', 'Ayuda', 186, 1),
  ('gw.home.card.normateca', 'Normateca', 186, 1),
  ('gw.home.asignaturas', 'Asignaturas', 186, 1),
  ('gw.home.col.nombreAsignatura', 'Nombre de la asignatura', 186, 1),
  ('gw.home.col.modalidad', 'Modalidad', 186, 1),
  ('gw.home.col.avance', 'Avance', 186, 1),
  ('gw.home.avance.error', 'No se pudo cargar el avance.', 186, 1),
  ('gw.home.avance.reintentar', 'Reintentar', 186, 1),
  ('gw.home.logros', 'Logros', 186, 1),
  ('gw.configuracionAreas.etiqueta.verConfig', 'Ver configuración de área', 170, 1),
  ('gw.configuracionAreas.etiqueta.distribucionesSeleccionadas', 'Distribuciones seleccionadas:', 170, 1),
  ('gw.public.cursos.buscar', 'Buscar cursos', 182, 1),
  ('gw.public.cursos.titulo', 'Cursos', 182, 1),
  ('gw.public.cursos.nuevo', 'Nuevo', 182, 1),
  ('gw.public.cursos.proximamente', 'Proximamente', 182, 1),
  ('gw.public.cursos.nivel', 'Nivel:', 182, 1),
  ('gw.public.cursos.duracion', 'Duración:', 182, 1),
  ('gw.public.cursos.contacto', 'Contacto', 182, 1),
  ('gw.public.cursos.eje', 'Eje de capacitación:', 182, 1),
  ('gw.public.cursos.tipoCompetencia', 'Tipo de competencia:', 182, 1),
  ('gw.public.cursos.modalidad', 'Modalidad:', 182, 1),
  ('gw.public.cursos.nivelEnsenanza', 'Nivel de enseñanza:', 182, 1),
  ('gw.public.cursos.cargaHoraria', 'Carga horaria registrada en el programa:', 182, 1),
  ('gw.public.cursos.nombre', 'Nombre', 182, 1),
  ('gw.public.cursos.correo', 'Correo electronico', 182, 1),
  ('gw.public.cursos.mensaje', 'Mensaje', 182, 1),
  ('gw.public.cursos.enviar', 'Enviar', 182, 1),
  ('gw.public.cursos.cancelar', 'Cancelar', 182, 1),
  ('gw.public.cursos.carousel.anterior', 'Anterior', 182, 1),
  ('gw.public.cursos.carousel.siguiente', 'Siguiente', 182, 1);

COMMIT;
