-- Nuevos textos para header, sidebar y login
INSERT INTO des_sisi_gestor.tbl_textos_sistema (clave, valor, id_funcionalidad, usuario_modifico) VALUES
  ('gw.header.toggleNavigation', 'Toggle navigation', 114, 1),
  ('gw.header.tooltip.tareas', 'Lista de tareas', 114, 1),
  ('gw.header.tooltip.notificaciones', 'Notificaciones', 114, 1),
  ('gw.header.tooltip.mensajes', 'Mensajes', 114, 1),
  ('gw.header.tooltip.reservaciones', 'Reservaciones', 114, 1),
  ('gw.header.bienvenida', '¡Bienvenido!', 114, 1),
  ('gw.header.perfil.alt', 'Usuario', 114, 1),
  ('gw.sidebar.menu', 'Menú', 114, 1),
  ('gw.sidebar.imagenesDocumentos', 'Imágenes de documentos', 114, 1),
  ('gw.sidebar.eventoAcademico', 'Evento académico', 114, 1),
  ('gw.sidebar.responsablesEventoAcademico', 'Responsables de eventos académicos', 114, 1),
  ('gw.sidebar.convocatorias', 'Convocatorias', 114, 1),
  ('gw.sidebar.inscripciones', 'Inscripciones', 114, 1),
  ('gw.sidebar.dispersiones', 'Dispersiones', 114, 1),
  ('gw.sidebar.expedienteEstudiantesGrupo', 'Expediente de estudiantes por grupo', 114, 1),
  ('gw.sidebar.cursosDisponibles', 'Cursos disponibles', 114, 1),
  ('gw.sidebar.asignaturasDisponibles', 'Asignaturas disponibles', 114, 1),
  ('gw.sidebar.inscripcion', 'Inscripción', 114, 1),
  ('gw.sidebar.misCursos', 'Mis cursos', 114, 1),
  ('gw.sidebar.tiraMaterias', 'Tira de materias', 114, 1),
  ('gw.sidebar.misLogros', 'Mis logros', 114, 1),
  ('gw.sidebar.historialAcademico', 'Historial académico', 114, 1),
  ('gw.sidebar.reporteUsuarios', 'Reporte de usuarios', 114, 1),
  ('gw.sidebar.reporteProgramas', 'Reporte de programas', 114, 1),
  ('gw.sidebar.reporteGestionEscolar', 'Reporte de gestión escolar', 114, 1),
  ('gw.sidebar.reporteEventosCapacitacion', 'Reporte de eventos de capacitación', 114, 1),
  ('gw.sidebar.reporteAmbientesVirtuales', 'Reporte de ambientes virtuales de aprendizaje', 114, 1),
  ('gw.sidebar.areasRecursos', 'Áreas y recursos', 114, 1),
  ('gw.sidebar.programas', 'Programas', 114, 1),
  ('gw.login.boton.iniciarSesion', 'Iniciar sesión', 47, 1);
