package mx.gob.sedesol.basegestor.commons.utils;

public enum ParametrosSistemaEnum {

	PS_CONFIG_CORREO_HOST("CONFIG_CORREO_HOST"),
	PS_CONFIG_CORREO_PUERTO("CONFIG_CORREO_PUERTO"),
	PS_CONFIG_CORREO_CUENTA_ADMIN("CONFIG_CORREO_CUENTA_ADMIN"),
	PS_CONFIG_CORREO_CUENTA_PASSWORD("CONFIG_CORREO_CUENTA_PASSWORD"),
	PS_TITULO_NOTIFICACION_CORREO("TITULO_NOTIFICACION_CORREO"),
	PS_CONTENIDO_CORREO_ACTIVACION_CTA("CONTENIDO_CORREO_ACTIVACION_CTA"),
	PS_ASUNTO_CORREO_ACTIVACION_CTA("ASUNTO_CORREO_ACTIVACION_CTA"),
	PS_ASUNTO_CORREO_RECUP_PASSWORD("ASUNTO_CORREO_RECUP_PASSWORD"),

	PS_INSCRIPCIONES_SIN_RESTRICCION("INSCRIPCIONES_SIN_RESTRICCION"),
	PS_PROGRAMAS_A_MOSTRAR_POR_CONVOCATORIA("PROGRAMAS_A_MOSTRAR_POR_CONVOCATORIA"),
	PS_INFORMACION_EXTRA("INFORMACION_EXTRA"),
	PS_TERMINOS_CONDICIONES("TERMINOS_CONDICIONES"),
	PS_MOSTRAR_TERMINOS_CONDICIONES("MOSTRAR_TERMINOS_CONDICIONES");
	
	private String clave;
	
	private ParametrosSistemaEnum( String clave) {
		this.clave = clave;
	}

	/**
	 * @return the clave
	 */
	public String getClave() {
		return clave;
	}

}
